---
version: '3'

description: |
  This is used to run ansible builds on gh actions

vars:
  is_tag: false

tasks:
  init_role:
    desc: |
      This task is used to create the config.yaml file to initialize mirror builds
    cmds:
      - |
        cat <<EOF > {{ .USER_WORKING_DIR }}/config.yaml
        # created by init task for use with github actons
        upstream:
          repo: ghcr.io/bradfordwagner/ansible
          tag: 5.1.2
        builds:
          - { os: alpine_3.18      }
          - { os: alpine_3.19      }
          - { os: archlinux_latest }
          - { os: debian_bookworm  }
          - { os: ubuntu_mantic    }
          - { os: ubuntu_noble     }
