---
version: '3'

description: |
  This is used to run docker builds on gh actions

vars:
  is_tag: false

tasks:
  init:
    desc: |
      This task is used to create the config.yaml file to initialize custom builds
    cmds:
      - |
        cat <<EOF > {{ .USER_WORKING_DIR }}/config.yaml
        # created by init task for use with github actons
        target_repo: quay.io/bradfordwagner/ansible
        upstreams:
          - { repo: quay.io/bradfordwagner/base:3.0.0-alpine_3.18      , platforms: [linux/amd64        , linux/arm64] }
          - { repo: quay.io/bradfordwagner/base:3.0.0-alpine_3.19      , platforms: [linux/amd64        , linux/arm64] }
          - { repo: quay.io/bradfordwagner/base:3.0.0-archlinux_latest , platforms: [linux/amd64    ] }
          - { repo: quay.io/bradfordwagner/base:3.0.0-debian_bookworm  , platforms: [linux/amd64        , linux/arm64] }
          - { repo: quay.io/bradfordwagner/base:3.0.0-debian_bullseye  , platforms: [linux/amd64        , linux/arm64] }
          - { repo: quay.io/bradfordwagner/base:3.0.0-ubuntu_mantic    , platforms: [linux/amd64        , linux/arm64] }
          - { repo: quay.io/bradfordwagner/base:3.0.0-ubuntu_noble     , platforms: [linux/amd64        , linux/arm64] }
        EOF
      - |
        file={{ .USER_WORKING_DIR }}/generate_dockerfile.sh
        cat <<EOF > ${file}
        # this is used to generate a docker file in the build task
        # input 0 is expected to be the nth upstream item
        v=\$1
        cat <<FOF
        RUN echo hello world=\$v
        FOF
        EOF
        chmod +x ${file}
  build:
    desc: |
      This task is used to build the docker images
    vars:
      build: '{{ default "" .build }}'
      target_tag: '{{ default "latest" .target_tag }}'
      use_cache: '{{ default "false" .use_cache }}'
      progress: '{{ default "plain" .progress }}'
    cmds:
      - |
        cd {{ .USER_WORKING_DIR }}

        # resolve upstream - if none provided then use the first from config.yaml
        build=$(echo '{{ .build }}')
        if [[ "" == "{{ .build }}" ]]; then
          build=$(yq -oj '.builds[0]' config.yaml | jq -rc '.')
        fi

        echo -n build=
        echo ${build} | jq '.'
        exit

        # setup go vars
        {{- $push_flag := eq "true" .is_tag | ternary "--push" " " }}
        {{- $use_cache := eq "true" .use_cache | ternary "" "--no-cache" }}

        # resolve shell vars
        os=$(echo ${build} | jq -r '.os')
        platforms=$(echo ${build} | jq -r '.platforms | join(",")')
        upstream_tag=$(yq -r '.upstream.tag' config.yaml)
        push_flag={{ $push_flag }}
        use_cache={{ $use_cache }}
        repo=$(yq -r '.upstream.repo' config.yaml):$(yq -r '.upstream.tag' config.yaml)-${os}

        # debug vars
        echo -n build=
        echo ${build} | jq '.'
        echo repo=${repo}
        echo platforms=${platforms}
        echo upstream_tag=${upstream_tag}
        echo use_cache=${use_cache}
        echo push_flag=${push_flag}


        # create the dockerfile
        generate_dockerfile=$(. generate_dockerfile.sh ${build})
        cat <<EOF > Dockerfile
        FROM ${repo}
        RUN mkdir /src
        WORKDIR /src
        COPY . .
        ${generate_dockerfile}
        EOF

        set -x

        # run build
        target_repo=$(yq -r '.target_repo' config.yaml)
        docker buildx build \
          --progress={{ .progress }} \
          ${use_cache} \
          --platform ${platforms} \
          -t ${target_repo}:{{ .target_tag }}-${upstream_tag} \
          {{ $push_flag }} \
          .
