---
version: '3'

description: |
  This is used to run docker builds on gh actions

tasks:
  default:
    cmds:
      - |
        echo '
        FROM alpine
        ' | docker buildx build --platform linux/amd64 -t hello-world -
    # ' | docker buildx build --platform linux/amd64,linux/arm64 -t hello-world -
