---
version: '3'

description: |
  This is used to write secrets to the repo

env:
  VAULT_ADDR: http://bradfordwagner.com:8200
  VAULT_FORMAT: json

tasks:
  default:
    desc: |
      reads secrets from vault and writes them to the repo
    cmds:
      # - vault status | jq
      # - vault list secrets
