---
version: '3'
env:
tasks:
  clear:
    internal: true
    cmds: [clear]
  default:
    vars:
      playbook: '{{ .playbook | default "playbook.yml" }}'
      location: '{{ .location }}'
    cmds:
      - task: clear
      - |
        ansible-playbook \
          -i localhost, -c local \
          {{ .playbook | quote }}
