# gh auth refresh --scopes 'admin:public_key','gist','read:org','repo','write:packages'
---
version: '3'

env:
  wd: '{{ .USER_WORKING_DIR }}'

vars:
  gh_token:
    sh: gh auth token
  gh_user:
    sh: whoami

tasks:
  default:
    cmds:
      - |
        cd ${wd}
        {{ .build_cmds }}
  ansible_role:
    desc: |
      Runs act for ansible role locally
    cmds:
      - |
        cd ${wd}

        act push -W ./.github/workflows/ansible_role_branches.yml \
          -r \
          --insecure-secrets \
          -s GITHUB_TOKEN={{ .gh_token }} \
          -P arm64=catthehacker/ubuntu:act-latest
  ansible_playbook:
    desc: |
      Runs act for ansible playbook locally
    cmds:
      - |
        cd ${wd}

        act push -W ./.github/workflows/ansible_playbook_branches.yml \
          -r \
          --insecure-secrets \
          -s GITHUB_TOKEN={{ .gh_token }} \
          -P arm64=catthehacker/ubuntu:act-latest
  custom:
    desc: |
      Runs act for custom builds
    cmds:
      - |
        cd ${wd}

        act push -W ./.github/workflows/docker_custom_branches.yml \
          -r \
          --insecure-secrets \
          -s GITHUB_TOKEN={{ .gh_token }} \
          -P arm64=catthehacker/ubuntu:act-latest
  mirror:
    desc: |
      Runs act for mirror builds
    cmds:
      - |
        cd ${wd}

        act push -W ./.github/workflows/docker_mirror_branches.yml \
          -r \
          --insecure-secrets \
          -s GITHUB_TOKEN={{ .gh_token }} \
          -P arm64=catthehacker/ubuntu:act-latest
