# gh auth refresh --scopes 'admin:public_key','gist','read:org','repo','write:packages'
---
version: '3'

env:
  wd: '{{ .USER_WORKING_DIR }}'

vars:
  gh_token:
    sh: gh auth token
  gh_user:
    sh: whoami
  dagger_modules: /Users/bwagner/workspace/github/bradfordwagner/go.lib/bradfordwagner.go.lib.dagger.container.builds
  image: ghcr.io/catthehacker/ubuntu:act-latest

tasks:
  auth:
    cmds:
      - gh auth login -s write:packages
  copy_dagger_modules:
    desc: |
      Copies dagger_modules to the workspace
    cmds:
      - |
        cd ${wd}
        rm -rf dagger_modules
        rsync -av --exclude='.git' {{ .dagger_modules }}/* dagger_modules/
  ansible_role:
    desc: |
      Runs act for ansible role locally
    cmds:
      - |
        cd ${wd}

        act push -W ./.github/workflows/ansible_role_branches.yml \
          -r \
          --insecure-secrets \
          -s GITHUB_TOKEN={{ .gh_token }} \
          -P arm64={{ .image }} \
          -P ubuntu-latest={{ .image }} \
          -P ubuntu-24.04-arm={{ .image }} \
          -P ubuntu-24.04={{ .image }} \
          --container-architecture linux/arm64
  ansible_playbook:
    desc: |
      Runs act for ansible playbook locally
    cmds:
      - |
        cd ${wd}

        act push -W ./.github/workflows/ansible_playbook_branches.yml \
          -r \
          --insecure-secrets \
          -s GITHUB_TOKEN={{ .gh_token }} \
          -P arm64={{ .image }} \
          -P ubuntu-latest={{ .image }} \
          -P ubuntu-24.04-arm={{ .image }} \
          -P ubuntu-24.04={{ .image }} \
          --container-architecture linux/arm64
  custom:
    desc: |
      Runs act for custom builds
    cmds:
      - |
        cd ${wd}

        act push -W ./.github/workflows/docker_custom_branches.yml \
          -r \
          --insecure-secrets \
          -s GITHUB_TOKEN={{ .gh_token }} \
          -P arm64={{ .image }} \
          -P ubuntu-latest={{ .image }} \
          -P ubuntu-24.04-arm={{ .image }} \
          -P ubuntu-24.04={{ .image }} \
          --container-architecture linux/arm64
  mirror:
    desc: |
      Runs act for mirror builds
    vars:
      dagger_modules: '{{ default .dagger_modules .default_dagger_modules }}'
    cmds:
      - task: copy_dagger_modules
      - |
        cd ${wd}
        act push -W ./.github/workflows/docker_mirror_branches.yml \
          --container-options="-v {{ .dagger_modules }}" \
          -r \
          --insecure-secrets \
          -s GITHUB_TOKEN={{ .gh_token }} \
          -P arm64={{ .image }} \
          -P ubuntu-latest={{ .image }} \
          -P ubuntu-24.04-arm={{ .image }} \
          -P ubuntu-24.04={{ .image }} \
          --container-architecture linux/arm64
  container:
    desc: |
      Runs act for mirror builds
    cmds:
      - task: copy_dagger_modules
      - |
        cd ${wd}
        image=ghcr.io/catthehacker/ubuntu:act-latest
        act push -W ./.github/workflows/container_branches.yml \
          --rm \
          --insecure-secrets \
          -s GITHUB_TOKEN={{ .gh_token }} \
          -P arm64={{ .image }} \
          -P ubuntu-latest={{ .image }} \
          -P ubuntu-24.04-arm={{ .image }} \
          -P ubuntu-24.04={{ .image }} \
          --container-architecture linux/arm64
