# https://taskfile.dev

version: '3'

env:
  wd: '{{ .USER_WORKING_DIR }}'

tasks:
  default:
    vars:
      debug: '{{ default "false" .debug }}'
      test_file: '{{ default "test.yml" .test_file }}'
    env:
      debug: '{{ .debug }}'
      test_file: '{{ .test_file }}'
    cmds:
      - |
        cd ${wd}
        [[ "true" == "{{ .debug }}" ]] && ansible -m setup localhost || echo Skipping Host Debug
        [ -f meta/requirements.yml ] && ansible-galaxy install -r meta/requirements.yml || echo "Skipping Role Dependency Download: No requirements.yml Found"
        set -e
        ansible-playbook ${test_file}
