---
version: '3'

description: |
  This is used to accomodate docker commands

tasks:
  k3d_image_import:
    desc: |
      This task is used to import the image into the k3d cluster
    vars:
      image: "{{ .image }}"
      cluster: '{{ default "dev-tkgi-hal" .cluster }}'
    cmds:
      - |
        set -x
        k3d image import {{ .image }} --cluster {{ .cluster }}
  push_tarball:
    desc: |
      This task is used to push the tarball to the docker registry
    vars:
      tarball: "{{ default .tarball }}"
      image_name: "{{ .image_name }}"
      image_tag: "{{ .image_tag }}"
      docker_registry: "{{ .docker_registry }}"
    cmds:
      - |
        set -x
        orig_image_name=$(docker image load -i {{ .tarball }}  --quiet \
          | sed 's|^[^:]*: *||'
        )
        new_image_name={{ .docker_registry }}/{{ .image_name }}:{{ .image_tag }}
        docker tag $orig_image_name {{ .docker_registry }}/{{ .image_name }}:{{ .image_tag }}
        docker push $new_image_name
