# https://taskfile.dev
#
# we can't use cookie cutter for these tasks
#   it is necessary for us to rev all the repositories
#   cookiecutter may not be the right choice for that

version: '3'

vars:
  task_version: 3.35.1
  default_steps: |
    - uses: actions/checkout@v4
    - name: Setup go-task
      uses: pnorton5432/setup-task@v1
      with:
        task-version: {{ .task_version }}
    - name: task version
      run: task --version
    - name: checkout taskfiles
      uses: actions/checkout@v4
      with:
        path: taskfiles
        repository: bradfordwagner/taskfiles
# todo: setup buildkit
# initially use mirror task
tasks:
  mkdir:
    internal: true
    cmds:
      - mkdir -p {{ .USER_WORKING_DIR }}/.github/workflows
  ansible_role:
    cmds:
      - task: mkdir
        ignore_error: true
      - |
        cat <<EOF > {{ .USER_WORKING_DIR }}/.github/workflows/ansible_role.yml
        name: ansible_role
        on: push
        jobs:
          ansible-role:
            strategy:
              fail-fast: false
              matrix:
                os:
                  - alpine_3.16
                  - alpine_3.17
                  # - archlinux_latest
                  - debian_bookworm
                  - debian_bullseye
                  - ubuntu_focal
                  # - ubuntu_kinetic
                  - ubuntu_lunar
                tag: [3.6.2]
            runs-on: ubuntu-latest
            container:
              image: {{ `quay.io/bradfordwagner/ansible:\${{ matrix.tag }}-\${{ matrix.os }}`}}
            steps:
              {{- .default_steps | nindent 6 -}}
              - name: Invoke Ansible Role Test
                run: task -t ./taskfiles/tasks/ansible_role.yml
        EOF
