---
version: '3'

description: |
  This is used to write secrets to the repo


env:
  VAULT_ADDR: http://bradfordwagner.com:8200
  VAULT_FORMAT: json
  kv2_prefix: secret/gh

tasks:
  github_quay:
    desc: |
      reads quay login secret from vault and fans it to filesystem
    internal: true
    cmds:
      - |
        cd {{ .USER_WORKING_DIR }}
        login_command=$(vault kv get ${kv2_prefix}/quay | jq -r '.data.data.login_command')
        echo ${login_command} | gh secret set QUAY_LOGIN
  vault_quay:
    desc: |
      var.login_command='docker login ... quay.io'
    cmds:
      - |
        vault kv put ${kv2_prefix}/quay \
          login_command="{{ .login_command }}"
  setup_container_mirror:
    desc: |
      Set up required secrets for a container mirror build
    cmds:
      - task: github_quay
