# https://taskfile.dev
#
#
# we can't use cookie cutter for these tasks
#   it is necessary for us to rev all the repositories
#   cookiecutter may not be the right choice for that

version: '3'

tasks:
  mkdir:
    internal: true
    cmds:
      - mkdir -p {{ .USER_WORKING_DIR }}/.github/workflows
  hello_world_action:
    cmds:
      - task: mkdir
        ignore_error: true
      - |
        cat <<EOF > {{ .USER_WORKING_DIR }}/.github/workflows/hello-world-action.yml
        name: hello-world
        on: push
        jobs:
          my-job:
            runs-on: ubuntu-latest
            steps:
              - name: my-step
                run: echo "Hello World!"
        EOF
