---
# todo: setup buildkit
# initially use mirror task
# - handle on tag:
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-of-specific-tags-occurs

version: '3'

vars:
  task_version: 3.35.1
  on_tags: |
    on:
      push:
        tags:
          - '*'
  on_branches: |
    on:
      - push
      - workflow_dispatch
  default_steps: |
    - name: checkout=self
      uses: actions/checkout@v4
    - name: task={{ .task_version }}
      uses: pnorton5432/setup-task@v1
      with:
        task-version: {{ .task_version }}
    - name: checkout=taskfiles
      uses: actions/checkout@v4
      with:
        path: taskfiles
        repository: bradfordwagner/taskfiles

tasks:
  mkdir:
    internal: true
    cmds:
      - mkdir -p {{ .USER_WORKING_DIR }}/.github/workflows
  ansible_role:
    cmds:
      - task: mkdir
        ignore_error: true
      - |
        cat <<EOF > {{ .USER_WORKING_DIR }}/.github/workflows/ansible_role.yml
        name: ansible_role
        on:
          - push
          - workflow_dispatch
        jobs:
          ansible-role:
            strategy:
              fail-fast: false
              matrix:
                os:
                  - alpine_3.16
                  - alpine_3.17
                  # - archlinux_latest
                  - debian_bookworm
                  - debian_bullseye
                  - ubuntu_focal
                  # - ubuntu_kinetic
                  - ubuntu_lunar
                tag: [3.6.2]
            runs-on: ubuntu-latest
            container:
              image: {{ `quay.io/bradfordwagner/ansible:\${{ matrix.tag }}-\${{ matrix.os }}`}}
            steps:
              {{- .default_steps | nindent 6 -}}
              - name: task=branches
                run: task -t ./taskfiles/tasks/ansible_role.yml
        EOF
  yaml_lint:
    cmds:
      - task: mkdir
        ignore_error: true
      - |
        cat <<EOF > {{ .USER_WORKING_DIR }}/.github/workflows/yaml_lint.yml
        name: yaml_lint
        on: push
        jobs:
          yaml-lint:
            runs-on: ubuntu-latest
            steps:
              {{- .default_steps | nindent 6 -}}
              - name: Install yamllint
                run: pip install --user yamllint
              - name: Invoke YAML Lint
                run: task -t ./taskfiles/tasks/yaml_lint.yml
        EOF
  go_releaser:
    vars:
      go_version: 1.21
      goreleaser_version: 1.24.0
    cmds:
      - task: mkdir
        ignore_error: true
      - for: [tags, branches]
        cmd: |
          cat <<EOF > {{ .USER_WORKING_DIR }}/.github/workflows/go_releaser_{{ .ITEM }}.yml
          name: go_releaser_{{ .ITEM }}
          {{- if eq .ITEM "tags" }}
          {{ .on_tags -}}
          {{- else }}
          {{ .on_branches -}}
          {{- end -}}
          jobs:
            go-releaser-{{ .ITEM }}:
              runs-on: ubuntu-latest
              steps:
                {{- .default_steps | nindent 6 -}}
                - name: go={{ .go_version }}
                  uses: actions/setup-go@v5
                  with:
                    go-version: {{ .go_version }}
                - name: goreleaser={{ .goreleaser_version }}
                  uses: goreleaser/goreleaser-action@v5
                  with:
                    version: {{ .goreleaser_version }}
                    install-only: true
                - name: task={{ .ITEM }}
                  run: task -t ./taskfiles/tasks/go_releaser.yml is_tag={{ eq .ITEM "tags" }}
                  env:
                    GITHUB_TOKEN: {{ `\${{ github.token }} `}}
          EOF
