---
version: '3'

description: |
  This is used to write secrets to the repo

includes:
  vault: ./vault.yml

env:
  VAULT_ADDR: https://bradfordwagner.com:8200
  VAULT_FORMAT: json
  kv2_prefix: secret/gh

tasks:
  github_ansible_galaxy:
    desc: |
      reads ansible galaxy secret from vault and fans it github
    internal: true
    cmds:
      - |
        cd {{ .USER_WORKING_DIR }}
        login_command=$(vault kv get ${kv2_prefix}/ansible | jq -r '.data.data.token')
        echo ${login_command} | gh secret set GALAXY_TOKEN
  github_quay:
    desc: |
      reads quay login secret from vault and fans it to filesystem
    internal: true
    cmds:
      - |
        cd {{ .USER_WORKING_DIR }}
        login_command=$(vault kv get ${kv2_prefix}/quay | jq -r '.data.data.login_command')
        echo ${login_command} | gh secret set QUAY_LOGIN
  vault_quay:
    desc: |
      var.login_command='docker login ... quay.io'
    cmds:
      - |
        vault kv put ${kv2_prefix}/quay \
          login_command="{{ .login_command }}"
  vault_ansible_role:
    desc: |
      var.token='https://galaxy.ansible.com/ui/token/'
    cmds:
      - |
        vault kv put ${kv2_prefix}/ansible \
          token="{{ .token }}"
  setup_ansible_role:
    desc: |
      Set up required secrets for an ansible role build
    cmds:
      - task: github_ansible_galaxy
  setup_container_mirror:
    desc: |
      Set up required secrets for a container mirror build
    cmds:
      - task: github_quay

  github_terraform:
    desc: |
      reads infra sp secret and fans it to github
    vars:
      role:
        sh: yq -r '.secrets.auth.approle.role' {{ .USER_WORKING_DIR }}/config.yaml
      ttl: '{{ default "30d" .ttl }}'
    cmds:
      - task: vault:generate_approle
        vars:
          role: '{{ .role }}'
          ttl: '{{ .ttl }}'
      - |
        cd {{ .USER_WORKING_DIR }}
        . {{ .env_secrets_file }}
        rm -f {{ .env_secrets_file }}
        echo ${role_id} | gh secret set ROLE_ID
        echo ${secret_id} | gh secret set SECRET_ID
