---
# todo: setup buildkit
# initially use mirror task
# - handle on tag:
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-of-specific-tags-occurs

version: '3'

vars:
  task_version: 3.35.1
  default_steps: |
    - uses: actions/checkout@v4
    - name: Setup go-task
      uses: pnorton5432/setup-task@v1
      with:
        task-version: {{ .task_version }}
    - name: task version
      run: task --version
    - name: checkout taskfiles
      uses: actions/checkout@v4
      with:
        path: taskfiles
        repository: bradfordwagner/taskfiles

tasks:
  mkdir:
    internal: true
    cmds:
      - mkdir -p {{ .USER_WORKING_DIR }}/.github/workflows
  ansible_role:
    cmds:
      - task: mkdir
        ignore_error: true
      - |
        cat <<EOF > {{ .USER_WORKING_DIR }}/.github/workflows/ansible_role.yml
        name: ansible_role
        on: push
        jobs:
          ansible-role:
            strategy:
              fail-fast: false
              matrix:
                os:
                  - alpine_3.16
                  - alpine_3.17
                  # - archlinux_latest
                  - debian_bookworm
                  - debian_bullseye
                  - ubuntu_focal
                  # - ubuntu_kinetic
                  - ubuntu_lunar
                tag: [3.6.2]
            runs-on: ubuntu-latest
            container:
              image: {{ `quay.io/bradfordwagner/ansible:\${{ matrix.tag }}-\${{ matrix.os }}`}}
            steps:
              {{- .default_steps | nindent 6 -}}
              - name: Invoke Ansible Role Test
                run: task -t ./taskfiles/tasks/ansible_role.yml
        EOF
  yaml_lint:
    cmds:
      - task: mkdir
        ignore_error: true
      - |
        cat <<EOF > {{ .USER_WORKING_DIR }}/.github/workflows/yaml_lint.yml
        name: yaml_lint
        on: push
        jobs:
          yaml-lint:
            runs-on: ubuntu-latest
            steps:
              {{- .default_steps | nindent 6 -}}
              - name: Install yamllint
                run: pip install --user yamllint
              - name: Invoke YAML Lint
                run: task -t ./taskfiles/tasks/yaml_lint.yml
        EOF
