---
# todo: setup buildkit
# initially use mirror task
# - handle on tag:
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-of-specific-tags-occurs

version: '3'

vars:
  task_version: 3.35.1
  buildx_version: v0.13.1
  on_tags: |
    on:
      push:
        tags:
          - '*'
  on_branches: |
    on:
      - push
      - workflow_dispatch
  default_steps: |
    - name: checkout=self
      uses: actions/checkout@v4
    - name: task={{ .task_version }}
      uses: pnorton5432/setup-task@v1
      with:
        task-version: {{ .task_version }}
    - name: checkout=taskfiles
      uses: actions/checkout@v4
      with:
        path: taskfiles
        repository: bradfordwagner/taskfiles

tasks:
  mkdir:
    internal: true
    cmds:
      - mkdir -p {{ .USER_WORKING_DIR }}/.github/workflows
  ansible_role:
    cmds:
      - task: mkdir
        ignore_error: true
      - |
        cat <<EOF > {{ .USER_WORKING_DIR }}/.github/workflows/ansible_role.yml
        name: ansible_role
        on:
          - push
          - workflow_dispatch
        jobs:
          ansible-role:
            strategy:
              fail-fast: false
              matrix:
                os:
                  - alpine_3.16
                  - alpine_3.17
                  # - archlinux_latest
                  - debian_bookworm
                  - debian_bullseye
                  - ubuntu_focal
                  # - ubuntu_kinetic
                  - ubuntu_lunar
                tag: [3.6.2]
            runs-on: ubuntu-latest
            container:
              image: {{ `quay.io/bradfordwagner/ansible:\${{ matrix.tag }}-\${{ matrix.os }}`}}
            steps:
              {{- .default_steps | nindent 6 -}}
              - name: task=branches
                run: task -t ./taskfiles/tasks/ansible_role.yml
        EOF
  yaml_lint:
    cmds:
      - task: mkdir
        ignore_error: true
      - |
        cat <<EOF > {{ .USER_WORKING_DIR }}/.github/workflows/yaml_lint.yml
        name: yaml_lint
        on: push
        jobs:
          yaml-lint:
            runs-on: ubuntu-latest
            steps:
              {{- .default_steps | nindent 6 -}}
              - name: Install yamllint
                run: pip install --user yamllint
              - name: Invoke YAML Lint
                run: task -t ./taskfiles/tasks/yaml_lint.yml
        EOF
  go_releaser:
    vars:
      go_version: 1.21
      goreleaser_version: 1.24.0
    cmds:
      - task: mkdir
        ignore_error: true
      - for: [tags, branches]
        cmd: |
          cat <<EOF > {{ .USER_WORKING_DIR }}/.github/workflows/go_releaser_{{ .ITEM }}.yml
          name: go_releaser_{{ .ITEM }}
          {{- if eq .ITEM "tags" }}
          {{ .on_tags -}}
          {{- else }}
          {{ .on_branches -}}
          {{- end -}}
          jobs:
            go-releaser-{{ .ITEM }}:
              runs-on: ubuntu-latest
              steps:
                {{- .default_steps | nindent 6 -}}
                - name: go={{ .go_version }}
                  uses: actions/setup-go@v5
                  with:
                    go-version: {{ .go_version }}
                - name: goreleaser={{ .goreleaser_version }}
                  uses: goreleaser/goreleaser-action@v5
                  with:
                    version: {{ .goreleaser_version }}
                    install-only: true
                - name: task={{ .ITEM }}
                  run: task -t ./taskfiles/tasks/go_releaser.yml is_tag={{ eq .ITEM "tags" }}
                  env:
                    GITHUB_TOKEN: {{ `\${{ github.token }} `}}
          EOF
  helm:
    vars:
      helm_version: v3.14.3
    cmds:
      - task: mkdir
        ignore_error: true
      - for: [branches]
        cmd: |
          cat <<EOF > {{ .USER_WORKING_DIR }}/.github/workflows/helm_{{ .ITEM }}.yml
          name: helm-{{ .ITEM }}
          {{ .on_branches -}}
          jobs:
            helm_{{ .ITEM }}:
              runs-on: ubuntu-latest
              steps:
                {{- .default_steps | nindent 6 -}}
                - name: helm={{ .helm_version }}
                  uses: azure/setup-helm@v4.1.0
                  with:
                     version: '{{ .helm_version }}'
                - name: task={{ .ITEM }}
                  run: task -t ./taskfiles/tasks/helm.yml
          EOF
  container_mirror:
    vars:
      config: 
        sh: cat {{ .USER_WORKING_DIR }}/config.yaml | yq
    cmds:
      - task: mkdir
        ignore_error: true
      - for: [branches,tags]
        cmd: |
          {{- $c := fromJson .config -}}
          {{- $root := . -}}
          cat <<EOF > {{ .USER_WORKING_DIR }}/.github/workflows/docker_mirror_{{ .ITEM }}.yml
          name: docker-mirror-{{ .ITEM }}
          {{- if eq .ITEM "tags" }}
          {{ .on_tags -}}
          {{- else }}
          {{ .on_branches -}}
          {{- end -}}
          jobs:
          {{- range $_, $v := $c.mirrors }}
          {{- with $root }}
            {{ $v.repo }}_{{ $v.tag | replace "." "-" }}_{{ .ITEM }}:
              name: {{ $v.repo }}:{{ $v.tag }}
              runs-on: ubuntu-latest
              steps:
                {{- .default_steps | nindent 6 -}}
                - name: qemu
                  uses: docker/setup-qemu-action@v3
                - name: docker_buildx={{ .buildx_version }}
                  uses: docker/setup-buildx-action@v3
                  with:
                    version: {{ .buildx_version }}
                - name: login=quay.io
                  run: docker login -u="{{ `\${{ secrets.QUAY_USER }}`}}" -p="{{ `\${{ secrets.QUAY_PASSWORD }}`}}" quay.io
                - name: task={{ .ITEM }}
                  run: |
                    {{ $ci_tag := `\${{ github.ref }}` }}
                    task -t ./taskfiles/tasks/containers/mirror.yml \
                      build \
                      repo={{ $v.repo }} \
                      repo_tag={{ $v.tag }} \
                      platforms={{ $v.platforms | join "," }} \
                      target_repo={{ $c.target_repo }} \
                      target_tag={{ eq .ITEM "tags" | ternary $ci_tag "latest" }} \
                      is_tag={{ eq .ITEM "tags" }}
          {{- end }}
          {{ end }}
          EOF

