---
version: '3'

description: |
  This is used to build go releaser binaries

vars:
  is_tag: false

env:
  wd: '{{ .USER_WORKING_DIR }}'

tasks:
  build_current_os_arch_only:
    desc: |
      This task is used to build the current os and arch only
    cmds:
      - |
        cd ${wd}
        set -ex
        goreleaser build --snapshot --single-target --clean
  default:
    cmds:
      - |
        cd ${wd}
        set -ex
        goreleaser check
        {{ if eq "true" .is_tag -}}
          goreleaser release
        {{- else }}
          # requires env.GITHUB_TOKEN
          goreleaser build --snapshot --clean
        {{- end }}
        ls -lh dist
