---
version: '3'

description: |
  task helper for helm

tasks:
  lint:
    cmds:
      - helm lint {{ .USER_WORKING_DIR }}
  template:
    vars:
      pipe_bat: '{{ default "false" .pipe_bat }}'
      debug: '{{ default "false" .debug }}'
      focus: '{{ default "" .focus }}'
    cmds:
      - |
        args={{- eq "true" .debug | ternary "--debug" "" }}
        if [[ "" != "{{ .focus }}" ]]; then
          args="${args} -s {{ .focus }}"
        fi
        set -x
        [[ "true" == "{{ .pipe_bat }}" ]] && helm template {{ default "release-name" .release_name }} {{ .USER_WORKING_DIR }} ${args} | bat -P -lyaml
        [[ "false" == "{{ .pipe_bat }}" ]] && helm template {{ default "release-name" .release_name }} {{ .USER_WORKING_DIR }} ${args}
  action_multiple:
    vars:
      focus: '{{ default "a,b,c" .focus }}'
      release_name: '{{ default "release-name" .release_name }}'
      output_dir: '{{ default "/tmp/templates" .output_dir }}'
      action: '{{ default "apply" .action }}'
    cmds:
      - mkdir -p {{ .output_dir }}
      - for: {var: focus, split: ','}
        cmd: |
          item={{ .ITEM }}
          cleaned_path="${item#./}"
          output_file_name=$(basename ${cleaned_path} .yaml)
          file_path={{ .output_dir }}/${output_file_name}.yaml
          cd {{ .USER_WORKING_DIR }} && helm template {{ .release_name }} {{ .USER_WORKING_DIR }} -s ${cleaned_path} > ${file_path}
          kubectl {{ .action }} -f ${file_path}
  dependencies:
    desc: installs helm dependencies
    vars:
      cleanup: '{{ default "true" .cleanup }}'
    cmds:
      - cmd: |
          [[ "true" == "{{ .cleanup }}" ]] && rm -rf {{ .USER_WORKING_DIR}}/charts {{ .USER_WORKING_DIR }}/Chart.lock
        ignore_error: true
      - cd {{ .USER_WORKING_DIR }} && helm dependency build
  registry_login:
    desc: logs into helm registry
    vars:
      helm_registry: "{{ .helm_registry }}"
      password: "{{ .password }}"
    cmds:
      - echo {{ .password }} | helm registry login {{ .helm_registry }} --username $(whoami) --password-stdin
  push_oci:
    desc: pushes oci image to registry
    vars:
      tarball: "{{ .tarball }}"
      oci_name: "{{ .oci_name }}"
      oci_path: "{{ .oci_path }}"
      oci_version: "{{ .oci_version }}"
      helm_registry: "{{ .helm_registry }}"
    cmds:
      - cmd: |
          set -x
          chart_url=oci://{{ .helm_registry }}/{{ .oci_path }}

          # push to registry
          if helm show chart "$chart_url/{{ .oci_name }}" --version "{{ .oci_version }}" --repository-config '' > /dev/null; then
            echo "$chart_url:{{ .oci_version }} already exists, skipping"
          else
            helm push "{{ .tarball }}" "$chart_url"
          fi
  default:
    cmds:
      - task: dependencies
      - task: lint
      - task: template
