---
version: '3'

description: |
  task helper for setting up home clusters for mba

vars:
  remote_host: bwagner-studio
  remote_dir: ~/.kube
  clusters: 'admin,cicd'
  install_dir: ~/.kube

tasks:
  default:
    cmds:
      - task: setup_cluster
        vars:
          cluster: '{{ .cluster }}'
        for: {var: clusters, split: ',', as: cluster}
  setup_cluster:
    internal: true
    vars:
      cluster: '{{ .cluster }}'
    cmds:
      - cmd: rm  {{ .install_dir }}/{{ .cluster }}
        ignore_error: true
      - |
        orig={{ .install_dir }}/{{ .cluster }}_tmp
        mod={{ .install_dir }}/{{ .cluster }}
        set -x
        # copy from remote
        rsync -av {{ .remote_host }}:{{ .remote_dir }}/{{ .cluster }} ${orig}
        # replace bind addr with dns name
        cat ${orig} | sed 's|https://0.0.0.0:|https://{{ .remote_host }}:|g' > ${mod}
        # cleanup tmp file
        rm ${orig}
        # set permissions
        chmod 600 ${mod}
        # smoketest
        KUBECONFIG=${mod} kubectl get po -A
