---
version: '3'

description: |
  task helper for kubectl

tasks:
  extract_cert_manager_certs:
    desc: vars{cert_secret=secret name to extract } extracts cert-manager tls.crt, tls.key, and ca.crt from a secret.
    vars:
      cert_secret: '{{ default "cnp-gateway-tls-cert" .cert_secret }}'
    env:
      cert_secret: '{{ .cert_secret }}'
    cmds:
      - kubectl get secrets ${cert_secret} -o json | jq '.data["ca.crt"]' -r  | base64 -d > {{ .USER_WORKING_DIR }}/ca.crt
      - kubectl get secrets ${cert_secret} -o json | jq '.data["tls.crt"]' -r | base64 -d > {{ .USER_WORKING_DIR }}/tls.crt
      - kubectl get secrets ${cert_secret} -o json | jq '.data["tls.key"]' -r | base64 -d > {{ .USER_WORKING_DIR }}/tls.key
  action_file:
    desc: runs kubectl action on file
    internal: true
    cmds:
      - cmd: kubectl {{ .action }} -f {{ .file }}
        ignore_error: true
  in_dir:
    aliases: [id, dir]
    desc: applies all files in present directory, non-recursive
    vars:
      action: '{{ default "apply" .action }}'
      files:
        sh: find {{ .USER_WORKING_DIR }} -type f -name '*.yaml' -o -name '*.yml' ! -name 'Taskfile.yml'
    cmds:
      - for: {var: files}
        task: action_file
        vars:
          action: '{{ .action }}'
          file: '{{ .ITEM }}'
