---
version: '3'

description: |
  task helper for kubefwd

tasks:
  ns:
    desc: forwards kubernetes services to localhost
    vars:
      ns: '{{ default "" .ns }}'
    cmds:
      - |
        ns="{{ .ns }}"
        if [[ -z ${ns} ]]; then
          ns=$(kubectl get ns -o json | qq -i json '.items | map(.metadata.name) | .[]' -r | fzf --multi)
        fi
        ns_args=""
        for namespace in ${ns}; do
          ns_args+=" -n ${namespace}"
        done
        cmd="sudo -E kubefwd svc${ns_args} -d cluster.local"
        echo "$cmd" | tmux load-buffer -
        eval "$cmd"
  all:
    desc: forwards kubernetes services to localhost
    cmds:
      - sudo -E kubefwd svc --all-namespaces -d cluster.local
