---
version: '3'

description: |
  task helper for tmux

tasks:
  split_window:
    desc: splits window with input directory
    internal: true
    cmds:
      - cmd: |
          tmux split-window -d -P -F '#{pane_index}' \
            | xargs -I % tmux send  -t % 'cd {{ .dir }}' Enter 'clear' Enter
        ignore_error: true
      - task: layout_tiled
  layout_tiled:
    internal: true
    desc: tiled layout
    cmds:
      - cmd: tmux select-layout tiled
  split_dirs:
    aliases: [sd]
    desc: opens dirs in new panes and tiles
    vars:
      dirs:
        # sed 1d removes the first line which is the current directory
        sh: find {{ .USER_WORKING_DIR }} -maxdepth 1 -type d -not -name '{{ .USER_WORKING_DIR }}' | sed '1d'
    cmds:
      - for: {var: dirs}
        task: split_window
        vars:
          dir: '{{ .ITEM }}'
