---
version: '3'

description: |
  This is used to write secrets to the repo

vars:
  vault_addr:
    sh: cat ~/.vault-addr
  vault_token:
    sh: cat ~/.vault-token
  vault_kubeconfig:
    sh: cat ~/.vault-kubeconfig
  env_secrets_file: "{{ .USER_WORKING_DIR }}/.secrets.sh"

env:
  KUBECONFIG: '{{ .vault_kubeconfig }}'
  VAULT_ADDR: '{{ .vault_addr }}'
  VAULT_FORMAT: json
  VAULT_TOKEN: '{{ .vault_token }}'

tasks:
  webpage:
    desc: |
      opens the vault
    cmds:
      - open "{{ .vault_addr }}"
  init:
    internal: false
    desc: |
      initializes the vault
    cmds:
      - vault operator init -key-shares=1 -key-threshold=1 -format=json > ~/.vault-init.json
      - jq -r '.unseal_keys_b64[0]' ~/.vault-init.json > ~/.vault-unseal-key
      - bat -P ~/.vault-addr
      - bat -P ~/.vault-kubeconfig
      - bat -P ~/.vault-unseal-key
      - bat -P ~/.vault-init.json
      - jq -r '.root_token' ~/.vault-init.json > ~/.vault-token
      - cp ~/.vault-token ~/.vault-root-token
      - cat ~/.vault-root-token | pbcopy
  logout:
    desc: |
      logs out of the vault
    cmds:
      - open "{{ .vault_addr }}/ui/vault/logout"
  unseal:
    internal: false
    desc: |
      unseals the vault
    cmds:
      - vault operator unseal "$(cat ~/.vault-unseal-key)" | jq
  reset:
    desc: |
      resets the vault and initializes vault
    cmds:
      - kubectl delete pvc --all &
      - kubectl delete pod --all --force=true
      - sleep 2
      - kubectl wait --for=condition=Ready pods --all --timeout=5m
      - task: init
      - task: unseal
  status:
    desc: |
      prints the status of the vault
    cmds:
      - bat -P ~/.vault-kubeconfig
      - |
        ns=$(kubectl config view --minify --output 'jsonpath={..namespace}')
        echo -n Kubernetes Namespace: ${ns}
      - vault status | jq
