---
version: '3'

description: |
  This is used to write secrets to the repo

vars:
  env_secrets_file: "{{ .USER_WORKING_DIR }}/.secrets.sh"

env:
  VAULT_ADDR: https://bradfordwagner.com:8200
  VAULT_FORMAT: json
  kv2_prefix: secret/gh

tasks:
  status:
    desc: |
      prints the status of the vault
    cmds:
      - vault status | jq
  clean_env_file:
    silent: true
    desc: |
      removes the secrets file
    cmds:
      - cmd: rm {{ .env_secrets_file }}
        ignore_error: true
  kv2_env:
    desc: |
      reads a secret from vault
    vars:
      path: '{{ default "secret/azure/sp/infra" .path }}'
    cmds:
      - |
        json_data=$(vault kv get {{ .path }}  | jq -r '.data.data')
        echo ${json_data} | jq -r 'to_entries | map("export \(.key)=\(.value | @sh)") | .[]' > {{ .env_secrets_file }}

  generate_approle:
    desc: |
      generates approle
    vars:
      role: '{{ default "gh_terraform" .role }}'
      ttl: '{{ default "10s" .ttl }}'
    env:
      role: '{{ .role }}'
      ttl: '{{ .ttl }}'
    cmds:
      - |
        cd {{ .USER_WORKING_DIR }}
        set -x
        echo using ttl=${ttl}
        role_id=$(vault read auth/approle/role/${role}/role-id | jq '.data.role_id' -r)
        secret_data=$(vault write -f auth/approle/role/${role}/secret-id ttl=${ttl})
        echo ${secret_data} | jq
        secret_id=$(echo ${secret_data} | jq '.data.secret_id' -r)
        cat <<EOF > {{ .env_secrets_file }}
        export role_id=${role_id}
        export secret_id=${secret_id}
        EOF
        vault write auth/approle/login role_id=${role_id} secret_id=${secret_id} | jq
  list_approle_accessors:
    desc: |
      lists approle accessors
    vars:
      role: '{{ default "gh_terraform" .role }}'
    env:
      role: '{{ .role }}'
    cmds:
      - |
        set -x
        vault list auth/approle/role/${role}/secret-id | jq
  read_approle_accessor:
    desc: |
      reads approle accessor
    vars:
      role: '{{ default "gh_terraform" .role }}'
      accessor: '{{ default "" .accessor }}'
    env:
      role: '{{ .role }}'
      accessor: '{{ .accessor }}'
    cmds:
      - |
        set -x
        vault write auth/approle/role/${role}/secret-id-accessor/lookup secret_id_accessor=${accessor} | jq
  delete_approle_accessors:
    desc: |
      deletes approle accessors
    vars:
      role: '{{ default "gh_terraform" .role }}'
    env:
      role: '{{ .role }}'
    cmds:
      - task: list_approle_accessors
      - vault list auth/approle/role/${role}/secret-id  | jq -r '.[]' | xargs -I % vault write auth/approle/role/${role}/secret-id-accessor/destroy secret_id_accessor=%
      - task: list_approle_accessors
  token_policies_for_auth_role:
    vars:
      vault_ns: '{{ default "" .vault_ns }}'
    env:
      VAULT_NAMESPACE: '{{ .vault_ns }}'
    desc: |
      lists the token policies for the auth role
    cmds:
      - |
        # 1. List auth mounts and select one
        mount=$(vault auth list -format=json | jq -r 'keys[]' | fzf --prompt="Select auth mount: ")
        mount=${mount%/} # Remove trailing slash if present
        echo "Selected mount: $mount"

        # 2. List roles for the selected mount and select one
        roles=$(vault list -format=json auth/${mount}/role | jq -r '.[]')
        role=$(echo "$roles" | fzf --prompt="Select role: ")
        echo "Selected role: $role"

        # 3. Get token policies for the selected role
        policies=$(vault read -format=json auth/${mount}/role/${role} | jq -r '.data.token_policies[]')
        echo "Policies for role ${role}: $policies"

        # 4. Read and view each policy in bat
        echo "${policies}" \
        | xargs -I {} sh -c 'echo "### policy={} ###"; vault policy read {} | jq -r ".policy"' \
        | bat -lhcl
