name: yaml_lint
on: push
jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout=self
        uses: actions/checkout@v4
      - name: task=3.35.1
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.35.1
      - name: checkout=taskfiles
        uses: actions/checkout@v4
        with:
          path: taskfiles
          repository: bradfordwagner/taskfiles
      - name: install=yamllint
        run: pip install --user yamllint
      - name: run=yamllint
        run: task -t ./taskfiles/tasks/yaml_lint.yml
